### ISSUE TITLE
Release last version

### ISSUE THREAD

**Issue by cpommier** [skratchdot/elasticsearch-tools#15]
the current latest version installed with npm has a bug in export: it had the "_score" to the json document. This filed is removed in the latest version of the master branch.

If elastic-tools could be released on npm repository it would be easier to use as no post treatment would be necessary.

Thanks

**Comment by skratchdot** [comment]
@cpommier - sorry about this. i will publish when I get home from work today

**Comment by skratchdot** [comment]
@cpommier - I published v3.0.1: https://www.npmjs.com/package/elasticsearch-tools

Hopefully it works!

**Comment by cpommier** [comment]
Thanks a lot, I will test this as soon as possible

**Comment by skratchdot** [comment]
@cpommier - okay. thanks!  i forgot to close this out yesterday. i'm going to do so now- feel free to re-open if there are issues.
