### ISSUE TITLE
error: "You must pass in a valid --max option"

### ISSUE THREAD

**Issue by r--w** [skratchdot/elasticsearch-tools#2]
Input:
```
./node_modules/.bin/es-import-bulk --url http://xxxxxx --file index.json --max 1000
```

Output:
```
error: "You must pass in a valid --max option"
```

Installation:
```
npm install  elasticsearch-tools
```

Max argument is valid intiger.

**Comment by skratchdot** [comment]
Thanks for logging this.  I remember running into this a few months ago, but thought I had fixed it.  I might have only fixed it locally.  I'll push a fix for this later today when I get a few minutes to look at it.
