### ISSUE TITLE
No package elasticsearch-tools available

### ISSUE THREAD

**Issue by kaihua1987** [skratchdot/elasticsearch-tools#27]
when I install elasticsearch-tools, it shows no available package, anyone hit the issue? thanks a lot

[root@kaihua-master ~]# yum install elasticsearch-tools
Loaded plugins: fastestmirror, langpacks, versionlock
Loading mirror speeds from cached hostfile
 * base: mirror.san.fastserv.com
 * elrepo: repos.mia.lax-noc.com
 * epel: archive.linux.duke.edu
 * extras: centos.mirror.ndchost.com
 * updates: centos.mirror.ndchost.com
Excluding 3 updates due to versionlock (use "yum versionlock status" to show them)
No package elasticsearch-tools available.
Error: Nothing to do
[root@kaihua-master ~]# yum versionlock status
Loaded plugins: fastestmirror, langpacks, versionlock
Loading mirror speeds from cached hostfile
 * base: mirror.san.fastserv.com
 * elrepo: repos.mia.lax-noc.com
 * epel: archive.linux.duke.edu
 * extras: centos.mirror.ndchost.com
 * updates: centos.mirror.ndchost.com
0:kubectl-1.13.4-0.*
0:kubeadm-1.13.4-0.*
0:kubelet-1.13.4-0.*
versionlock status done
[root@kaihua-master ~]#

**Comment by skratchdot** [comment]
The tools are installed via `npm` not `yum`: https://www.npmjs.com/
